#' @title gearByYear
#' @description This function generates a tibble that lists how many occurrences of a variety of 
#' gear types were observed each year
#' @param df  this is a dataframe likely generated by BFT_LOGS(). 
#' @author  Mike McMahon, \email{Mike.McMahon@@dfo-mpo.gc.ca}
#' @importFrom dplyr %>%
gearByYear <- function(df){
  res<- df %>%
    dplyr::filter(BFT_LANDED_WEIGHT_LBS > 0) %>% 
    dplyr::mutate(YEAR = ifelse(!is.na(LANDING_DATE_TIME), lubridate::year(lubridate::ymd(substr(LANDING_DATE_TIME, 1, 10))),
                         ifelse(!is.na(FV_FISHED_DATETIME), lubridate::year(lubridate::ymd(substr(FV_FISHED_DATETIME, 1, 10))), NA))) %>% 
    dplyr::group_by(YEAR, gear_code) %>%
    dplyr::summarise(COUNT = length(gear_code), .groups = "keep") %>%
    tidyr::pivot_wider(names_from = gear_code, values_from = COUNT, values_fill = 0)
  
  missing_cols <- setdiff(c("51", "54","60","61","81","85", "NA"), names(res))
  for(col in missing_cols){
    res <- res %>% dplyr::mutate(!!rlang::sym(col) := 0)
  }
  res <- res %>% dplyr::select(YEAR, "51", "54","60","61","81","85", "NA")
  return(res)
}